obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: .18
footprint_padding: 0.01
inflation_radius: 0.50
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
